
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          132465
     no. of nonzeroes in lower triangle of a =         4784064
     no. of nonzeroes in the factor l        =        40640210
     ratio of nonzeroes in factor (min/max)  =          0.5971
     number of super nodes                   =            4862
     maximum order of a front matrix         =            1893
     maximum size of a front matrix          =         1792671
     maximum size of a front trapezoid       =         1022010
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.3880D+10
     no. of floating point ops for solve     =      1.5321D+08
     ratio of flops for factor (min/max)     =          0.4442
     ratio of allocated memory (max/min)     =          1.8240
     number of positive pivots               =          132459
     number of negative pivots               =               6
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =               6
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =               6
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.015625        0.004117
     time (cpu & wall) for ordering          =        0.109375        0.116406
     time (cpu & wall) for other matrix prep =        0.015625        0.016360
     time (cpu & wall) for value input       =        0.015625        0.009666
     time (cpu & wall) for matrix distrib.   =        0.078125        0.080566
     time (cpu & wall) for numeric factor    =        0.265625        0.255381
     computational rate (gflops) for factor  =       89.901882       93.508191
     time (cpu & wall) for numeric solve     =        0.015625        0.021797
     computational rate (gflops) for solve   =        9.805270        7.028698
     effective I/O rate (GB/sec) for solve   =       36.530375       26.186018

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        229376.        2. MB        220071.        2. MB
                95-   1        229376.        2. MB        220177.        2. MB
                95-   2        393216.        3. MB        362051.        3. MB
                95-   3        557056.        4. MB        536549.        4. MB

                -------     ----------     --------     ----------     --------
                Totals:       1409024.       11. MB       1338848.       10. MB


  Solver Memory allocated on core    0       =      144.879 MB
  Solver Memory allocated on core    1       =      139.768 MB
  Solver Memory allocated on core    2       =      232.945 MB
  Solver Memory allocated on core    3       =      254.939 MB
  Total Solver Memory allocated by all cores =      772.531 MB

