
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          924483
     no. of nonzeroes in lower triangle of a =        34589517
     no. of nonzeroes in the factor l        =       481855142
     ratio of nonzeroes in factor (min/max)  =          0.5278
     number of super nodes                   =           32856
     maximum order of a front matrix         =            6138
     maximum size of a front matrix          =        18840591
     maximum size of a front trapezoid       =        11431266
     ParMETIS reordering method used (speed) 
     ParMETIS method 2 used
     no. of floating point ops for factor    =      7.9834D+11
     no. of floating point ops for solve     =      1.8539D+09
     ratio of flops for factor (min/max)     =          0.5495
     ratio of allocated memory (max/min)     =          1.8720
     number of positive pivots               =          924477
     number of negative pivots               =               6
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =               6
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =               6
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.031250        0.033203
     time (cpu & wall) for ordering          =        1.171875        1.170847
     time (cpu & wall) for other matrix prep =        0.187500        0.197964
     time (cpu & wall) for value input       =        0.093750        0.095195
     time (cpu & wall) for matrix distrib.   =        0.843750        0.851836
     time (cpu & wall) for numeric factor    =        7.203125        7.207815
     computational rate (gflops) for factor  =      110.831804      110.759689
     time (cpu & wall) for numeric solve     =        0.250000        0.251416
     computational rate (gflops) for solve   =        7.415498        7.373734
     effective I/O rate (GB/sec) for solve   =       27.627077       27.471478

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1671168.       13. MB       1654745.       13. MB
                95-   1       1671168.       13. MB       1652238.       13. MB
                95-   2       2293760.       18. MB       2283924.       17. MB
                95-   3       3866624.       30. MB       3841589.       29. MB

                -------     ----------     --------     ----------     --------
                Totals:       9502720.       72. MB       9432496.       72. MB


  Solver Memory allocated on core    0       =     1463.553 MB
  Solver Memory allocated on core    1       =     1474.260 MB
  Solver Memory allocated on core    2       =     2178.656 MB
  Solver Memory allocated on core    3       =     2739.700 MB
  Total Solver Memory allocated by all cores =     7856.169 MB

