
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          147735
     no. of nonzeroes in lower triangle of a =        12341421
     no. of nonzeroes in the factor l        =       195053851
     ratio of nonzeroes in factor (min/max)  =          0.9824
     number of super nodes                   =            2488
     maximum order of a front matrix         =            5571
     maximum size of a front matrix          =        15520806
     maximum size of a front trapezoid       =         8622051
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      4.5530D+11
     no. of floating point ops for solve     =      7.6451D+08
     ratio of flops for factor (min/max)     =          0.9147
     ratio of allocated memory (max/min)     =          1.1806
     number of positive pivots               =          147729
     number of negative pivots               =               6
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =              16
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =              12
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.016200
     time (cpu & wall) for ordering          =        0.203125        0.217325
     time (cpu & wall) for other matrix prep =        0.046875        0.033742
     time (cpu & wall) for value input       =        0.031250        0.033884
     time (cpu & wall) for matrix distrib.   =        0.156250        0.158657
     time (cpu & wall) for numeric factor    =        2.781250        2.799897
     computational rate (gflops) for factor  =      163.702890      162.612671
     time (cpu & wall) for numeric solve     =        0.062500        0.075577
     computational rate (gflops) for solve   =       12.232139       10.115639
     effective I/O rate (GB/sec) for solve   =       45.571885       37.686685

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        360448.        3. MB        328100.        3. MB
                95-   1        327680.        2. MB        321732.        2. MB
                95-   2        327680.        2. MB        320544.        2. MB
                95-   3        327680.        2. MB        305158.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1343488.       10. MB       1275534.       10. MB


  Solver Memory allocated on core    0       =      898.629 MB
  Solver Memory allocated on core    1       =      782.990 MB
  Solver Memory allocated on core    2       =      888.414 MB
  Solver Memory allocated on core    3       =      761.180 MB
  Total Solver Memory allocated by all cores =     3331.213 MB

