
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =         2403765
     no. of nonzeroes in lower triangle of a =       198162765
     no. of nonzeroes in the factor l        =      4258852726
     ratio of nonzeroes in factor (min/max)  =          0.8859
     number of super nodes                   =           39496
     maximum order of a front matrix         =           12585
     maximum size of a front matrix          =        79197405
     maximum size of a front trapezoid       =        43963590
     ParMETIS reordering method used (speed) 
     ParMETIS method 2 used
     no. of floating point ops for factor    =      1.9835D+13
     no. of floating point ops for solve     =      1.6785D+10
     ratio of flops for factor (min/max)     =          0.8358
     ratio of allocated memory (max/min)     =          1.1695
     number of positive pivots               =         2403759
     number of negative pivots               =               6
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-05
     number of 1x1 pivots                    =               6
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =               6
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.250000        0.239497
     time (cpu & wall) for ordering          =        4.531250        4.595996
     time (cpu & wall) for other matrix prep =        0.562500        0.572158
     time (cpu & wall) for value input       =        0.484375        0.496030
     time (cpu & wall) for matrix distrib.   =        3.078125        3.122578
     time (cpu & wall) for numeric factor    =      109.750000      110.720152
     computational rate (gflops) for factor  =      180.733077      179.149458
     time (cpu & wall) for numeric solve     =        1.703125        1.716317
     computational rate (gflops) for solve   =        9.855457        9.779707
     effective I/O rate (GB/sec) for solve   =       36.717354       36.435138

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0    1269432320.     9685. MB    1199816602.     9154. MB
                95-   1    1124040704.     8576. MB    1062466307.     8106. MB
                95-   2    1239678976.     9458. MB    1172448430.     8945. MB
                95-   3    1204224000.     9188. MB    1138510069.     8686. MB

                -------     ----------     --------     ----------     --------
                Totals:    4837376000.    36906. MB    4573241408.    34891. MB


  Solver Memory allocated on core    0       =    13073.847 MB
  Solver Memory allocated on core    1       =    11178.609 MB
  Solver Memory allocated on core    2       =    12973.583 MB
  Solver Memory allocated on core    3       =    12093.411 MB
  Total Solver Memory allocated by all cores =    49319.450 MB

