
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          335172
     no. of nonzeroes in lower triangle of a =        25962504
     no. of nonzeroes in the factor l        =       281689866
     ratio of nonzeroes in factor (min/max)  =          0.7229
     number of super nodes                   =            6359
     maximum order of a front matrix         =            3567
     maximum size of a front matrix          =         6363528
     maximum size of a front trapezoid       =         3694323
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      3.7808D+11
     no. of floating point ops for solve     =      1.0957D+09
     ratio of flops for factor (min/max)     =          0.6606
     ratio of allocated memory (max/min)     =          1.3803
     number of positive pivots               =          335166
     number of negative pivots               =               6
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =               6
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =               6
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.015625        0.018819
     time (cpu & wall) for ordering          =        0.437500        0.459375
     time (cpu & wall) for other matrix prep =        0.062500        0.052124
     time (cpu & wall) for value input       =        0.046875        0.052118
     time (cpu & wall) for matrix distrib.   =        0.343750        0.332830
     time (cpu & wall) for numeric factor    =        2.890625        2.896882
     computational rate (gflops) for factor  =      130.795457      130.512969
     time (cpu & wall) for numeric solve     =        0.109375        0.102151
     computational rate (gflops) for solve   =       10.017417       10.725879
     effective I/O rate (GB/sec) for solve   =       37.320748       39.960184

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        786432.        6. MB        770622.        6. MB
                95-   1        688128.        5. MB        681129.        5. MB
                95-   2        688128.        5. MB        676274.        5. MB
                95-   3        622592.        5. MB        599515.        5. MB

                -------     ----------     --------     ----------     --------
                Totals:       2785280.       21. MB       2727540.       21. MB


  Solver Memory allocated on core    0       =     1381.220 MB
  Solver Memory allocated on core    1       =     1112.896 MB
  Solver Memory allocated on core    2       =     1186.160 MB
  Solver Memory allocated on core    3       =     1000.660 MB
  Total Solver Memory allocated by all cores =     4680.935 MB

