
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          303363
     no. of nonzeroes in lower triangle of a =        11050911
     no. of nonzeroes in the factor l        =       106813291
     ratio of nonzeroes in factor (min/max)  =          0.8304
     number of super nodes                   =           10918
     maximum order of a front matrix         =            2166
     maximum size of a front matrix          =         2346861
     maximum size of a front trapezoid       =         1079358
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      6.7439D+10
     no. of floating point ops for solve     =      4.0500D+08
     ratio of flops for factor (min/max)     =          0.5718
     ratio of allocated memory (max/min)     =          1.1613
     number of positive pivots               =          303357
     number of negative pivots               =               6
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =               6
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =               6
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.015625        0.008321
     time (cpu & wall) for ordering          =        0.281250        0.276906
     time (cpu & wall) for other matrix prep =        0.046875        0.043048
     time (cpu & wall) for value input       =        0.031250        0.030427
     time (cpu & wall) for matrix distrib.   =        0.156250        0.163846
     time (cpu & wall) for numeric factor    =        0.625000        0.622216
     computational rate (gflops) for factor  =      107.901751      108.384522
     time (cpu & wall) for numeric solve     =        0.046875        0.043659
     computational rate (gflops) for solve   =        8.639995        9.276326
     effective I/O rate (GB/sec) for solve   =       32.189043       34.559750

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        720896.        6. MB        717904.        5. MB
                95-   1        786432.        6. MB        755628.        6. MB
                95-   2        786432.        6. MB        784252.        6. MB
                95-   3        720896.        6. MB        709036.        5. MB

                -------     ----------     --------     ----------     --------
                Totals:       3014656.       23. MB       2966820.       23. MB


  Solver Memory allocated on core    0       =      499.574 MB
  Solver Memory allocated on core    1       =      498.275 MB
  Solver Memory allocated on core    2       =      465.239 MB
  Solver Memory allocated on core    3       =      430.188 MB
  Total Solver Memory allocated by all cores =     1893.276 MB

