
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          117093
     no. of nonzeroes in lower triangle of a =         4296777
     no. of nonzeroes in the factor l        =        41221788
     ratio of nonzeroes in factor (min/max)  =          0.4445
     number of super nodes                   =            4326
     maximum order of a front matrix         =            1803
     maximum size of a front matrix          =         1626306
     maximum size of a front trapezoid       =         1083444
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.5285D+10
     no. of floating point ops for solve     =      1.5584D+08
     ratio of flops for factor (min/max)     =          0.8170
     ratio of allocated memory (max/min)     =          2.2856
     number of positive pivots               =          117087
     number of negative pivots               =               6
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =               6
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =               6
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.003772
     time (cpu & wall) for ordering          =        0.109375        0.102128
     time (cpu & wall) for other matrix prep =        0.015625        0.014084
     time (cpu & wall) for value input       =        0.000000        0.009581
     time (cpu & wall) for matrix distrib.   =        0.078125        0.086361
     time (cpu & wall) for numeric factor    =        0.281250        0.275050
     computational rate (gflops) for factor  =       89.900574       91.927122
     time (cpu & wall) for numeric solve     =        0.015625        0.021389
     computational rate (gflops) for solve   =        9.973849        7.286223
     effective I/O rate (GB/sec) for solve   =       37.158431       27.145451

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        229376.        2. MB        218298.        2. MB
                95-   1        229376.        2. MB        197800.        2. MB
                95-   2        327680.        2. MB        307511.        2. MB
                95-   3        491520.        4. MB        488115.        4. MB

                -------     ----------     --------     ----------     --------
                Totals:       1277952.       10. MB       1211724.        9. MB


  Solver Memory allocated on core    0       =      142.741 MB
  Solver Memory allocated on core    1       =      127.990 MB
  Solver Memory allocated on core    2       =      189.592 MB
  Solver Memory allocated on core    3       =      292.539 MB
  Total Solver Memory allocated by all cores =      752.862 MB

